name: Build pull request

on: pull_request

concurrency: ${{ github.ref }}

jobs:
  build_python:
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bot
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: |
            bot/requirements.txt
            bot/requirements-dev.txt
      - run: pip install -r requirements.txt -r requirements-dev.txt
      - run: |
          black --check .
          python -m py_compile main.py
  build_node:
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: ^10.14.0
      - uses: actions/setup-node@v4
        with:
          node-version: ^22.18.0
          cache: "pnpm"
      - run: |
          pnpm install --frozen-lockfile
          pnpm run check
          pnpm run lint
